### ISSUE TITLE
Error: "toString()" failed

### ISSUE THREAD

**Issue by KwankiAhn** [almeida/redis-mass#2]
Hello~ this is Ahn.
I'm trying to make : csv -> input file -> resp file
- input file :
DEL f2ejjkdsl4839tuj3984utvm00000001_01
SADD f2ejjkdsl4839tuj3984utvm00000001_01 3001 3002 3003 3004 3005 3006 3007 3008 3009 1010
DEL f2ejjkdsl4839tuj3984utvm00000002_01
SADD f2ejjkdsl4839tuj3984utvm00000002_01 3001 3002 3003 3004 3005 3006 3007 3008 3009 1010
.....

- redis-mass throws error like below, it looks huge file can't be handled.
do you have any idea ?

1330000000 Nov 13 23:30 input_commands.txt

$ redis-mass input_commands.txt | redis-cli -h {xxx.xxx.xxx.xxx} --pipe

buffer.js:495
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Object.<anonymous> (/usr/lib/node_modules/redis-mass/lib/redis-mass.js:12:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
All data transferred. Waiting for the last reply...
Last reply received from server.
errors: 0, replies: 0

**Comment by almeida** [comment]
Hello Ahn! I have just published a new redis-mass version. Version 0.3.0 should support large files.

**Comment by KwankiAhn** [comment]
Great!! I've tested with over 300MB & it works well. Thank you :+1:
